apiVersion: v1
kind: Pod
metadata:
  name: app
  namespace: webapp
spec:
  containers:
  - name: app
    image: 195651259892.dkr.ecr.us-east-1.amazonaws.com/a1-dev-app:v1.0
    ports:
    - containerPort: 8080
    env:
    - name: DBHOST
      value: <mysql-pod IP>
    - name: DBPORT
      value: "3306"
    - name: DBUSER
      value: root
    - name: DBPWD
      valueFrom:
        secretKeyRef:
          name: app
          key: password
  imagePullSecrets:
  - name: ecrcredapp