apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-v2
  namespace: webapp
  labels:
    app: employees
    version: v2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employees
      version: v2
  template:
    metadata:
      labels:
        app: employees
        version: v2
    spec:
      containers:
      - name: app
        image: 195651259892.dkr.ecr.us-east-1.amazonaws.com/a1-dev-app:v2.0
        ports:
        - containerPort: 8080
        env:
        - name: DBHOST
          value: mysql.sqldb.svc.cluster.local
        - name: DBPORT
          value: "3306"
        - name: DBUSER
          value: root
        - name: DBPWD
          valueFrom:
            secretKeyRef:
              name: app
              key: password
      imagePullSecrets:
        - name: ecrcredapp