apiVersion: v1
kind: Pod
metadata:
  name: mysql
  namespace: sqldb
spec:
  containers:
  - name: mysql
    image: 195651259892.dkr.ecr.us-east-1.amazonaws.com/a1-dev-mysql:v1.0
    ports:
    - containerPort: 3306
    env:
    - name: MYSQL_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mysql
          key: password
  imagePullSecrets:
  - name: ecrcreddb
